name: Test and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4
        with:
          version: 10

      - name: "Setup"
        run: pnpm install

      - name: "Build Frontend"
        run: pnpm build:frontend

      - name: "Test"
        run: |
          pnpm fmt
          pnpm lint
          pnpm test --testTimeout 15000

      - name: "Deploy"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          pnpm wrangler deploy
