name: PR Tests
on:
  pull_request:

jobs:
  coverage-goshujin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: goshujin

      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4
        with:
          version: 10

      - name: "Run Test with Coverage"
        run: |
          pnpm install
          pnpm build:frontend
          pnpm coverage --testTimeout 15000

      - name: "Upload Coverage"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-goshujin
          path: coverage

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.ref }}

      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@02f6c237bd2518259fed6c71566509edfb3f2b74 # v4
        with:
          version: 9

      - name: "Install Deps"
        run: pnpm install

      - name: "Build Frontend"
        run: pnpm build:frontend

      - name: "Lint"
        run: |
          pnpm prettier -c .
          pnpm lint

      - name: "Type Check"
        run: pnpm typecheck

      - name: "Run Test with Coverage"
        run: pnpm coverage --testTimeout 15000

      - name: "Upload Coverage"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-head
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Download HEAD coverage artifacts"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-head
          path: coverage

      - name: "Download goshujin coverage artifacts"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-goshujin
          path: coverage-goshujin

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@2500dafcee7dd64f85ab689c0b83798a8359770e # v2
        with:
          json-summary-compare-path: coverage-goshujin/coverage-summary.json
